User_CRUD_Latest/Pages/User/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using USER_CRUD.DataObjects;
using USER_CRUD.Pages.DataObjects;

namespace User_Crud_New.Pages.User
{
    public class IndexModel : PageModel
    {
        public CommonTasks Common_Tasks { get; set; }
        public IEnumerable<UserModel> Users { get; set; }
        public IndexModel(CommonTasks commonTasks)
        {
            Common_Tasks = commonTasks;
        }

        public async Task<IActionResult> OnGet()
        {
            Users = await UserModel.GetAllUsersAsync(Common_Tasks.DatabaseConnectionString);
            return Page();
        }

        public async Task<IActionResult> OnPostDeactivateUserAsync(Guid PKey)
        {
            try
            {
                var userModel = await UserModel.GetUserAsync(PKey, Common_Tasks.DatabaseConnectionString);
                userModel.LastUpdatedOn = DateTime.UtcNow;
                userModel.Active = false;

                using (var connection = new SqlConnection(Common_Tasks.DatabaseConnectionString))
                {
                    await connection.OpenAsync();
                    using SqlTransaction transaction = connection.BeginTransaction();
                    await connection.ExecuteAsync(@"exec dbo.UpdateUserDetails @PKey", new { userModel.PKey }, transaction);
                    transaction.Commit();
                }

                return Redirect("/User/Index");
            }
            catch (Exception ex)
            {
                return Redirect("/Error");
            }
        }
    }
}

User_CRUD_Latest/Pages/User/ManageSkill.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using USER_CRUD.Pages.DataObjects;
using User_CRUD_Latest.DataObjects;

namespace User_CRUD_Latest.Pages.User
{
    public class ManageSkillModel : PageModel
    {
        [BindProperty]
        public SkillModel Skill { get; set; }
        public IEnumerable<SkillModel> Skills { get; set; }
        public CommonTasks Common_Tasks { get; set; }

        public ManageSkillModel(CommonTasks commonTasks)
        {
            Common_Tasks = commonTasks;
        }
        public async Task<IActionResult> OnGet(Guid? Pkey)
        {
            Skills = await SkillModel.GetAllSkillsAsync(Common_Tasks.DatabaseConnectionString);

            return Page();
        }

        public async Task<IActionResult> OnPostAddSkillAsync()
        {
            try
            {
                Skill.PKey = Guid.NewGuid();
                Skill.LastUpdatedOn = DateTime.UtcNow;
                Skill.Active = true;

                using (var connection = new SqlConnection(Common_Tasks.DatabaseConnectionString))
                {
                    await connection.OpenAsync();
                    using SqlTransaction transaction = connection.BeginTransaction();
                    await connection.ExecuteAsync(@"
Insert INTO [Skill](PKey,Name,Description,DisplayOrder,Active,LastUpdatedOn)
Values(@PKey,@Name,@Description,@DisplayOrder,@Active,@LastUpdatedOn)",
new { Skill.PKey, Skill.Name, Skill.Description, Skill.DisplayOrder, Skill.Active, Skill.LastUpdatedOn }, transaction);


                    transaction.Commit();
                }

                return Redirect("/User/ManageSkill");
            }
            catch (Exception ex)
            {
                return Redirect("/Error");
            }
        }

        public async Task<IActionResult> OnPostDeactivateSkillAsync(Guid PKey)
        {

            var skill = await SkillModel.GetSkillAsync(PKey, Common_Tasks.DatabaseConnectionString);

            var connection = new SqlConnection(Common_Tasks.DatabaseConnectionString);
            await connection.OpenAsync();
            using SqlTransaction transaction = connection.BeginTransaction();

            await connection.ExecuteAsync(@"UPDATE [dbo].[Skill] SET 
                                Active = 0,
                                [LastUpdatedOn] = GETUTCDATE()
                                WHERE [PKey] = @PKey and Active=1",
                          new
                          {
                              skill.PKey
                          },
                          transaction);
            transaction.Commit();

            return Redirect("/User/ManageSkill");
        }

    }
}

User_CRUD_Latest/Pages/User/ManageUser.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using USER_CRUD.DataObjects;
using USER_CRUD.Pages.DataObjects;
using User_CRUD_Latest.DataObjects;

namespace User_CRUD_Latest.Pages.User
{
    public class ManageUserModel : PageModel
    {
        public CommonTasks Common_Tasks { get; set; }
        public IEnumerable<SkillModel> Skills { get; set; }

        [BindProperty]
        public IEnumerable<Guid> SkillKey { get; set; }

        [BindProperty]
        public UserModel UserModel { get; set; }

        public IEnumerable<UserSkillModel> UserSkills { get; set; }

        public ManageUserModel(CommonTasks commonTasks)
        {
            Common_Tasks = commonTasks;
        }

        public async Task<IActionResult> OnGet(Guid? Pkey)
        {
            Skills = await SkillModel.GetAllSkillsAsync(Common_Tasks.DatabaseConnectionString);
            if (Pkey != null)
            {
                UserModel = await UserModel.GetUserAsync(Pkey.Value, Common_Tasks.DatabaseConnectionString);
                UserSkills = await UserSkillModel.GetUserSkillsAsync(Pkey.Value, Common_Tasks.DatabaseConnectionString);
                List<Guid> skillKey = new List<Guid>();
                foreach (var key in UserSkills)
                {
                    skillKey.Add(key.SkillKey);
                }

                SkillKey = skillKey.AsEnumerable();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAddUserAsync()
        {
            try
            {

                UserModel.PKey = Guid.NewGuid();
                UserModel.LastUpdatedOn = DateTime.UtcNow;
                UserModel.Active = true;

                using (var connection = new SqlConnection(Common_Tasks.DatabaseConnectionString))
                {
                    await connection.OpenAsync();
                    using SqlTransaction transaction = connection.BeginTransaction();
                    await connection.ExecuteAsync(@"
Insert INTO [User](PKey,Name,DOB,Designation,DisplayOrder,Active,LastUpdatedOn)
Values(@PKey,@Name,@DOB,@Designation,@DisplayOrder,@Active,@LastUpdatedOn)",
new { UserModel.PKey, UserModel.Name, UserModel.DOB, UserModel.Designation, UserModel.DisplayOrder, UserModel.Active, UserModel.LastUpdatedOn }, transaction);

                    foreach (var k in SkillKey)
                    {
                        await connection.ExecuteAsync(@"
Insert INTO [UserSkill](PKey,UserKey,SkillKey,Active,LastUpdatedOn)
Values(@PKey,@UserKey,@SkillKey,@Active,@LastUpdatedOn)",
new { PKey = Guid.NewGuid(), UserKey = UserModel.PKey, SkillKey = k, Active = true, LastUpdatedOn = DateTime.UtcNow }, transaction);

                    }

                    transaction.Commit();
                }

                return Redirect("./Index");
            }
            catch (Exception ex)
            {
                return Redirect("/Error");
            }
        }

        public async Task<IActionResult> OnPostSaveUserAsync()
        {
            try
            {
                UserModel.LastUpdatedOn = DateTime.UtcNow;
                UserModel.Active = true;

                using (var connection = new SqlConnection(Common_Tasks.DatabaseConnectionString))
                {
                    await connection.OpenAsync();
                    using SqlTransaction transaction = connection.BeginTransaction();
                    await connection.ExecuteAsync(@"
Update [dbo].[User] SET
Name=@Name,
DOB=@DOB,
Designation=@Designation,
DisplayOrder=@DisplayOrder,
LastUpdatedOn = @LastUpdatedOn,
Active=@Active
where Pkey=@Pkey and Active=1",
new { UserModel.PKey, UserModel.Name, UserModel.DOB, UserModel.Designation, UserModel.DisplayOrder, UserModel.Active, UserModel.LastUpdatedOn }, transaction);

                    await connection.ExecuteAsync(@"Delete from UserSkill where UserKey=@UserKey",new { UserKey = UserModel.PKey},transaction);
                    foreach (var k in SkillKey)
                    {
                        await connection.ExecuteAsync(@"
Insert INTO [UserSkill](PKey,UserKey,SkillKey,Active,LastUpdatedOn)
Values(@PKey,@UserKey,@SkillKey,@Active,@LastUpdatedOn)",
new { PKey = Guid.NewGuid(), UserKey = UserModel.PKey, SkillKey = k, Active = true, LastUpdatedOn = DateTime.UtcNow }, transaction);

                    }

                    transaction.Commit();
                }

                return Redirect("./Index");
            }
            catch (Exception ex)
            {
                return Redirect("/Error");
            }
        }

    }
}

User_CRUD_Latest/Pages/User/Index.cshtml
@page
@model User_Crud_New.Pages.User.IndexModel
@{
}

<div class="card shadow">
    <div class="card-header bg-primary">
        <h6 class="text-center pt-1 font-weight-bold text-white">List of Users</h6>
    </div>
    <div class="card-body">
        <a class="btn btn-outline-primary btn-sm" href="/User/ManageUser"><i class="fas fa-plus mr-2" aria-hidden="true" title="Add User"></i>Add User</a>
        <hr />
        @if (Model.Users != null)
        {
            <div>
                <table class="table table-striped table-bordered table-sm shadow-sm table-hover">
                    <thead>
                        <tr>
                            <th></th>
                            <th></th>
                            <th class="text-center">Name</th>
                            <th class="text-center">DOB</th>
                            <th class="text-center">Designation</th>
                            <th class="text-center">Skills</th>
                            <th class="text-center">Last Updated by</th>
                            <th class="text-center">Last Updated On</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var d in Model.Users)
                        {
                            <tr>
                                <td>
                                    <a class="btn btn-outline-primary btn-sm" id="EditUser" asp-page="./ManageUser" asp-route-Pkey="@d.PKey" title="Edit">
                                        Edit
                                        <i class="fas fa-edit"></i>
                                    </a>
                                </td>
                                <td>
                                    <form method="post" asp-page-handler="DeactivateUser" asp-route-pkey="@d.PKey" name="DeactivateUserForm" id="DeactivateUserForm"
                                          data-ajax="true" data-ajax-method="post" data-ajax-complete="DeactivateBankAccountCompleted">
                                        <button class="btn btn-outline-danger btn-sm ml-1" onclick="return confirm('Are you sure?');" id="EditUser" type="submit" title="Deactivate">
                                            Delete <i class="fas fa-trash-alt"></i>
                                        </button>
                                    </form>
                                </td>
                                <td class="text-wrap"> @d.Name </td>
                                <td class="text-wrap text-right"> @d.DOB?.ToString("d") </td>
                                <td class="text-wrap"> @d.Designation </td>
                                <td class="text-wrap"> @d.SkillNames </td>
                                <td class="text-wrap"> @d.LastUpdatedBy </td>
                                <td class="text-wrap text-right"> @d.LastUpdatedOn?.ToString("F") </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        }
    </div>
</div>

User_CRUD_Latest/Pages/User/ManageSkill.cshtml
@page
@model User_CRUD_Latest.Pages.User.ManageSkillModel
@{
}

<div class="card shadow">
    <div class="card-header bg-primary">
        <h6 class="text-center pt-1 font-weight-bold text-white">Add / Edit Skill</h6>
    </div>
    <div class="card-body">
        <a class="btn btn-outline-primary btn-sm" data-toggle="modal" href="#"
           data-target="#AddSkillModal"><span>Add Skill<i class="fas fa-plus" title="Add Skill"></i></span></a> &nbsp;

        <hr />
        @if (Model.Skills != null)
        {
            <div>
                <table class="table table-striped table-bordered table-sm shadow-sm table-hover">
                    <thead>
                        <tr>
                            @*<th></th>*@
                            <th></th>
                            <th class="text-center">Name</th>
                            <th class="text-center">Description</th>
                            <th class="text-center">Display Order</th>
                            <th class="text-center">Last Updated By</th>
                            <th class="text-center">Last Updated On</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var st in Model.Skills)
                        {
                            <tr>
                                @*<td>
                                        <a class="btn btn-outline-primary btn-sm" data-toggle="modal"
                                           data-target="#EditSkillModal" data-skillkey="@st.PKey"
                                           data-skillname="@st.Name" data-description="@st.Description"
                                           data-displayorder="@st.DisplayOrder" title="Edit" href="#">
                                            <span><i class="fas fa-edit"></i></span>
                                        </a>
                                    </td>*@
                                <td>
                                    <form method="post" asp-page-handler='DeactivateSkill' class="AreYouSureForm"
                                          data-ajax="true" data-ajax-method="post" data-ajax-complete="DeactivateSkillCompleted">
                                        <input type="hidden" id="PKey" name="PKey" value="@st.PKey" />
                                        <button type="submit" class="btn btn-outline-danger btn-sm" title="Deactivate"
                                                href="#" onclick="return confirm('Are you sure?');">
                                            Delete <span><i class="fas fa-trash-alt"></i></span>
                                        </button>
                                    </form>
                                </td>
                                <td>
                                    <a>@st.Name</a>
                                </td>
                                <td>
                                    <a>@st.Description</a>
                                </td>
                                <td class="text-right">
                                    <a>@st.DisplayOrder</a>
                                </td>
                                <td>
                                    @st.LastUpdatedBy
                                </td>
                                <td class="text-right">@st.LastUpdatedOn?.ToString("F")</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
    </div>
</div>
<div class="modal fade" id="AddSkillModal" tabindex="-1" role="dialog" aria-labelledby="AddSkillModal" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <form method="post" enctype="multipart/form-data" asp-page-handler="AddSkill"
                  data-ajax="true" data-ajax-method="post">
                <div id="app">
                    <div class="modal-header">
                        <h5 class="modal-title" id="AddSkillLabel">
                            Add Skill
                        </h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label='Close'>
                            <span aria-hidden="true"></span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <div class="form-row">
                                <div class="col">
                                    <label asp-for="Skill.Name" class="font-weight-bold">Name</label>
                                    <input type="text" class="form-control nameInputBox" asp-for="Skill.Name" aria-describedby="NameHelp" placeholder='Enter Skill Name' required>
                                    <small id="NameHelp" class="form-text text-muted">Name should be unique</small>
                                    <span asp-validation-for="Skill.Name" class="text-danger"></span>
                                </div>
                                <div class="col">
                                    <label asp-for="Skill.DisplayOrder" class="font-weight-bold">Display Order</label>
                                    <input type="number" class="form-control percentInputBox" min="-32767" max="32767" step="1" asp-for="Skill.DisplayOrder" required />
                                    <span asp-validation-for="Skill.DisplayOrder" class="text-danger"></span>
                                </div>
                            </div>
                            <br />
                            <div class="form-group">
                                <label for="Description" class="font-weight-bold">Description</label>
                                <textarea class="form-control" rows="3" asp-for="Skill.Description" placeholder='Description' required></textarea>
                            </div>
                            <br />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-outline-primary" type="submit">Save<i class="fas fa-save" title="Save"></i></button>
                        <button class="btn btn-outline-secondary" type="button" data-dismiss="modal">
                            Close<i class="fas fa-window-close" title="Close"></i>
                        </button>

                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

User_CRUD_Latest/Pages/User/ManageUser.cshtml
@page
@model User_CRUD_Latest.Pages.User.ManageUserModel
@{
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/Index"><i class="fas fa-home"></i></a></li>
        <li class="breadcrumb-item"><a href="/User/Index">List of Users</a></li>
        @if (Model.UserModel == null)
        {
            <li class="breadcrumb-item active" aria-current="page">Add User</li>
        }
        else
        {
            <li class="breadcrumb-item active" aria-current="page">Edit User</li>
        }
    </ol>
</nav>
<hr />
<div class="card shadow">
    <div class="card-header bg-primary">
        @if (Model.UserModel != null)
        {
            <h6 class="text-center pt-1 font-weight-bold text-white">Edit User Details</h6>
        }
        else
        {
            <h6 class="text-center pt-1 font-weight-bold text-white">Add User Details</h6>
        }
    </div>
    <div class="card-body">
        <form method="post" asp-page-handler='@(Model.UserModel == null ? "AddUser" : "SaveUser")'
              data-ajax="true" data-ajax-method="post" data-ajax-complete="AddOrUpdateUserCompleted">
            <div class="text-danger" asp-validation-summary="All" id="ValidationTop"></div>

            @if (Model.UserModel != null)
            {
                <input type="hidden" asp-for="UserModel.PKey" />
            }
            <button type="submit" class="btn btn-outline-primary" title="Save" href="#">Save<i class="fas fa-save"></i></button>

            <a class="btn btn-outline-secondary" href='/User/Index' title="Cancel">Cancel<i class="fas fa-window-close"></i></a>
            <hr />
            <div class="form-row">
                <div class="mt-2 col-lg-4">
                    <label asp-for="UserModel.Name" class="font-weight-bold">Name</label>
                    <input type="text" class="form-control nameInputBox" asp-for="UserModel.Name" placeholder='Enter Name' required>
                    <span asp-validation-for="UserModel.Name" class="text-danger"></span>
                </div>
                <div class="mt-2 col-lg-4">
                    <label asp-for="UserModel.Designation" class="font-weight-bold">Designation</label>
                    <input type="text" class="form-control nameInputBox" asp-for="UserModel.Designation" placeholder='Enter Designation' required>
                    <span asp-validation-for="UserModel.Designation" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="mt-2 col-lg-4">
                    <label asp-for="UserModel.DOB" class="font-weight-bold">DOB</label>
                    <input type="date" min="1990-01-01" max="2999-12-31" class="form-control percentInputBox" asp-for="UserModel.DOB" required />
                    <span asp-validation-for="UserModel.DOB" class="text-danger"></span>
                </div>
                <div class="mt-2 col-lg-4">
                    <label asp-for="UserModel.DisplayOrder" class="font-weight-bold">Display Order</label>
                    <input type="number" class="form-control nameInputBox" asp-for="UserModel.DisplayOrder" required>
                    <span asp-validation-for="UserModel.DisplayOrder" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="mt-2 col-lg-4">
                    <label asp-for="SkillKey" class="font-weight-bold">Skills</label>
                    <select multiple class="form-control w-auto" size="10" asp-for="SkillKey" required>
                        @foreach (var skill in Model.Skills)
                        {
                            <option value='@skill.PKey.ToString()'>@skill.Name</option>
                        }
                    </select>
                    <span asp-validation-for="SkillKey" class="text-danger"></span><br />
                </div>
            </div>
            <hr />
            <button type="submit" class="btn btn-outline-primary" title="Save" href="#">Save<i class="fas fa-save"></i></button>
            <a class="btn btn-outline-secondary" href='/User/Index' title="Cancel">Cancel<i class="fas fa-window-close"></i></a>
        </form>
    </div>
</div>